[skin]
default = "rgb(252, 232, 195) rgb(28, 27, 25)"
tree = "rgb(182, 168, 141) none"
file = "rgb(252, 232, 195) none"
directory = "rgb(104, 168, 228) none bold"
exe = "rgb(152, 188, 55) none"
link = "rgb(255, 92, 143) none"
pruning = "rgb(89, 73, 101) none Italic"
permissions = "rgb(182, 168, 141) none"
owner = "rgb(182, 168, 141) none"
group = "rgb(182, 168, 141) none"
selected_line = "none rgb(48, 48, 48)"
char_match = "rgb(251, 184, 41) none"
file_error = "rgb(247, 83, 65) none"
flag_label = "rgb(182, 168, 141) none"
flag_value = "rgb(251, 184, 41) none bold"
input = "rgb(252, 232, 195) none"
status_error = "rgb(247, 83, 65) rgb(38, 38, 38)"
status_job = "rgb(252, 232, 195) rgb(58, 58, 58)"
status_normal = "gray(20) rgb(38, 38, 38)"
status_italic = "rgb(251, 184, 41) rgb(38, 38, 38)"
status_bold = "rgb(251, 184, 41) none bold"
status_code = "rgb(81, 159, 80) rgb(38, 38, 38)"
status_ellipsis = "rgb(182, 168, 141) rgb(38, 38, 38)"
scrollbar_track = "rgb(38, 38, 38) none"
scrollbar_thumb = "rgb(251, 184, 41) none"
help_paragraph = "rgb(252, 232, 195) none"
help_bold = "rgb(252, 232, 195) none bold"
help_italic = "rgb(255, 92, 143) none italic"
help_code = "rgb(255, 92, 143) none"
help_headers = "rgb(251, 184, 41) none"
